### ISSUE TITLE
Error Installing afBeanUtils for fantom-lang.org

### ISSUE THREAD

**Issue by Donklord** [Fantom-Factory/afBeanUtils#1]
@SlimerDude  ran into the following error when trying to build this pod for fantom-lang.org.

C:\Users\Phillip Birch\Documents\GitHub\fantom-lang.org>fpm install afBeanUtils
ERROR: Env.index load: afBeanUtils
  java.util.zip.ZipException: zip file is empty
sys::IOErr: Could not find `/meta.props` in pod file: C:\fantom\fantom-1.0.73\lib\fan\afBeanUtils.pod
  afFpm::FileUtils$.readMetaProps (FileUtils.fan:36)
  afFpm::LocalDirRepository.readMetaProps (LocalDirRepository.fan:71)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:57)
  fan.sys.Func$Indirect0.call (Func.java:128)
  fan.sys.Map.getOrAdd (Map.java:168)
  afFpm::LocalDirRepository.getOrMake (LocalDirRepository.fan:56)
  afFpm::LocalDirRepository.resolve (LocalDirRepository.fan:40)
  afFpm::Resolver.doResolve (Resolver.fan:117)
  fan.sys.List.each (List.java:602)
  afFpm::Resolver.doResolve (Resolver.fan:116)
  afFpm::Resolver.resolve (Resolver.fan:105)
  fan.sys.Func$Indirect0.call (Func.java:128)
  fan.sys.Map.getOrAdd (Map.java:168)
  afFpm::Resolver.resolve (Resolver.fan:93)
  afFpm::InstallCmd.run (InstallCmd.fan:170)
  afFpm::Main.main (Main.fan:40)
  java.lang.reflect.Method.invoke (Unknown)
  fan.sys.Method.invoke (Method.java:573)
  fan.sys.Method$MethodFunc.callOn (Method.java:244)
  fan.sys.Method.callOn (Method.java:139)
  fanx.tools.Fan.callMain (Fan.java:185)
  fanx.tools.Fan.executeType (Fan.java:147)
  fanx.tools.Fan.execute (Fan.java:41)
  fanx.tools.Fan.run (Fan.java:308)
  fanx.tools.Fan.main (Fan.java:346)

**Comment by SlimerDude** [comment]
Unusual...

> sys::IOErr: Could not find /meta.props in pod file: C:\fantom\fantom-1.0.73\lib\fan\afBeanUtils.pod

That suggests the `afBeanUtils.pod` is corrupt if meta.props can't be found inside it. Try deleting it and updating again. Not that it makes a difference, but you shouldn't need to specify *afBeanUtils* - I believe just the following should do the trick:

    > fpm install

**Comment by Donklord** [comment]
Ok that fixed it, i now get an error when trying run an update on fantom-lang.org.  Ill make sure to post that in the issue forum over there :)
